### ISSUE TITLE
Guest book feature :3

### ISSUE THREAD

**Issue by akrossu** [Stankendesokies/stankendesokies.github.io#1]
HI! i saw your comment on endercatcore and checked out your website, it looks good!! I wanted to share a cool website that allows you to host website comments and stuff for static webpages https://www.htmlcommentbox.com/

I use it for my github pages website, idk how customizable the elements are in vanilla css, but some fancy js might do the trick, happy creating :3

**Comment by Stankendesokies** [comment]
Ohhhh!!! Thank you so much!
I will definitely make use of this <333

CSS is actually the only coding language I’m truly confident in (cuz I’ve
been writing in very regularly for the past like 4 years thanks to the
‘stylus’ extension on Firefox and ‘Vencord’ for Discord) so I’m sure I’ll
figure the styling out :3c

**Comment by Stankendesokies** [comment]
I've fucking done, I worked non stop on the guest book from 21:00 to 04:00 (no joke) 
IT'S FINALLY DONE!
Time for my next 2 month coding broke /j fufufufu
Closing this thread :3
